name: Smoke Suite
on:
  workflow_dispatch:
    save_artifacts:
      description: "Save Report in Artifact"
      required: true
      type: boolean
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run: npm install
        - name: Run Test
          run: npm run test-remote
          continue-on-error: true
        - name: Upload Allure Report to Artifact
          if: ${{ github.event.inputs.save_artifacts }}
          uses: actions/upload-artifact@v3
          with:
            name: AllureReport
            path: ./allure-report
